[build-system]
requires = ["setuptools", "wheel", "twine"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true
packages = ["LaserDisplay"]

[project]
name = "LaserDisplay"
description = ""
version = "0.1.0"
license-files = ["LICENSE"]
authors = [{name = "Matthias Kesenheimer", email = "m.kesenheimer@gmx.net"}]
dependencies = [
  "numpy",
  "pygame",
  "pysb",
  "twisted",
  "pycairo",
  "PyGObject",
]